#pragma once

#include "../../Globals.h"

#pragma pack(push, 1)
struct GameUpdatePacket
{
	uint8_t m_type;
	uint8_t m_byte1;
	uint8_t m_byte2;
	uint8_t m_byte3;
	int m_int1;
	int m_int2;
	int m_int3;
	float m_float1;
	int m_int4;
	float m_float2;
	float m_float3;
	float m_float4;
	float m_float5;
	float m_float6;
	uint32_t m_int5;
	uint32_t m_int6;
	uint32_t m_dataSize;
};
#pragma pack(pop)

enum
{
    NET_GAME_PACKET_STATE = 0,
    NET_GAME_PACKET_CALL_FUNCTION,
    NET_GAME_PACKET_UPDATE_STATUS,
    NET_GAME_PACKET_TILE_CHANGE_REQUEST,
    NET_GAME_PACKET_SEND_MAP_DATA,
    NET_GAME_PACKET_SEND_TILE_UPDATE_DATA,
    NET_GAME_PACKET_SEND_TILE_UPDATE_DATA_MULTIPLE,
    NET_GAME_PACKET_TILE_ACTIVATE_REQUEST,
    NET_GAME_PACKET_TILE_APPLY_DAMAGE,
    NET_GAME_PACKET_SEND_INVENTORY_STATE,
    NET_GAME_PACKET_ITEM_ACTIVATE_REQUEST,
    NET_GAME_PACKET_ITEM_ACTIVATE_OBJECT_REQUEST,
    NET_GAME_PACKET_SEND_TILE_TREE_STATE,
    NET_GAME_PACKET_MODIFY_ITEM_INVENTORY,
    NET_GAME_PACKET_ITEM_CHANGE_OBJECT,
    NET_GAME_PACKET_SEND_LOCK,
    NET_GAME_PACKET_SEND_ITEM_DATABASE_DATA,
    NET_GAME_PACKET_SEND_PARTICLE_EFFECT,
    NET_GAME_PACKET_SET_ICON_STATE,
    NET_GAME_PACKET_ITEM_EFFECT,
    NET_GAME_PACKET_SET_CHARACTER_STATE,
    NET_GAME_PACKET_PING_REPLY,
    NET_GAME_PACKET_PING_REQUEST,
    NET_GAME_PACKET_GOT_PUNCHED,
    NET_GAME_PACKET_APP_CHECK_RESPONSE,
    NET_GAME_PACKET_APP_INTEGRITY_FAIL,
    NET_GAME_PACKET_DISCONNECT,
    NET_GAME_PACKET_BATTLE_JOIN,
    NET_GAME_PACKET_BATTLE_EVENT,
    NET_GAME_PACKET_USE_DOOR,
    NET_GAME_PACKET_SEND_PARENTAL,
    NET_GAME_PACKET_GONE_FISHIN,
    NET_GAME_PACKET_STEAM,
    NET_GAME_PACKET_PET_BATTLE,
    NET_GAME_PACKET_NPC,
    NET_GAME_PACKET_SPECIAL,
    NET_GAME_PACKET_SEND_PARTICLE_EFFECT_V2,
    NET_GAME_PACKET_ACTIVE_ARROW_TO_ITEM,
    NET_GAME_PACKET_SELECT_TILE_INDEX,
    NET_GAME_PACKET_SEND_PLAYER_TRIBUTE_DATA, //39
    NET_GAME_PACKET_PVE_UNK1, //no names for these 5, so i named them unk. 
    NET_GAME_PACKET_PVE_UNK2,
    NET_GAME_PACKET_PVE_UNK3,
    NET_GAME_PACKET_PVE_UNK4,
    NET_GAME_PACKET_PVE_UNK5,
    NET_GAME_PACKET_SET_EXTRA_MODS,
    NET_GAME_PACKET_ON_STEP_ON_TILE_MOD,
    NET_GAME_PACKET_MAXVAL                    //not real, just for string overflow
};